version: '3.8'

services:
  postgres:
    build: 
      context: ./postgres
      dockerfile: Dockerfile
    ports:
     - "5432:5432"
    networks:
     - app-network

  postgis:
    build: 
      context: ./postgis
      dockerfile: Dockerfile
    ports:
      - "5432"
    depends_on:
      - postgres
    networks:
      - app-network
    volumes:
      - ./postgis/output:/output
    environment:
      POSTGRES_HOST: 0.0.0.0
      POSTGRES_DB: metro_santiago_3
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password


  flask-server:
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - postgis
    networks:
      - app-network
    volumes:
     - ./postgis/output:/output

networks:
  app-network:
    driver: bridge
