version: '3'
services:
  postgis:
    build:
      context: .
      dockerfile: Dockerfile.postgis
    ports:
      - "5433:5432"  # Cambiado el puerto de mapeo del contenedor
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/data
