version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    networks:
      - app-tier

  postgis:
    image: mdillon/postgis:latest
    environment:
      POSTGIS_DB: mydb
      POSTGIS_USER: myuser
      POSTGIS_PASS: mypassword
    depends_on:
      - postgres
    networks:
      - app-tier

  pgrouting:
    image: pgrouting/pgrouting:latest
    depends_on:
      - postgis
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
