# Utiliza la imagen oficial de PostgreSQL
FROM postgres:latest

# Define las variables de entorno para PostgreSQL
ENV POSTGRES_DB=mydb
ENV POSTGRES_USER=myuser
ENV POSTGRES_PASSWORD=mypassword
